In [1]:
import pandas as pd

In [5]:
df = pd.read_csv(r"../data/processed/clean_supply_chain.csv")
df.head()

,Product_ID,Warehouse,Order_Date,Shipment_Date,Lead_Time,Demand_Forecast,Inventory_Level,Stockout_Flag,Backorder_Flag,Supplier_ID,Order_Quantity,Shipment_Quantity,Product_Category,Product_Price,Customer_ID,Order_Priority,Revenue
0,8270,A,2023-01-01,2023-01-02,8,839,481,0,0,397,98,40,Clothing,387.89,2014,High,38013.22
1,1860,C,2023-01-01,2023-01-02,8,351,332,0,1,483,52,35,Furniture,891.03,6805,High,46333.56
2,6390,C,2023-01-01,2023-01-02,5,398,156,0,0,160,34,43,Food,933.21,3833,Medium,31729.14
3,6191,A,2023-01-01,2023-01-02,5,972,418,1,0,161,32,45,Electronics,628.57,3640,Medium,20114.24
4,6734,D,2023-01-01,2023-01-02,3,529,428,0,0,325,44,41,Electronics,70.33,9297,Medium,3094.52

In [6]:
warehouse_perf = (
    df.groupby('Warehouse')
      .agg({
          'Lead_Time':'mean',
          'Revenue':'sum',
          'Stockout_Flag':'mean',
          'Backorder_Flag':'mean'
      })
)

warehouse_perf

           Lead_Time      Revenue  Stockout_Flag  Backorder_Flag
Warehouse
A           4.977659  57412206.54       0.205541        0.162645
B           4.908725  55855897.16       0.194631        0.158389
C           4.958916  57502720.76       0.202257        0.149887
D           5.034602  59039313.87       0.203287        0.167820

In [9]:
supplier_perf = (
    df.groupby('Supplier_ID')
      .agg({
          'Lead_Time':'mean'
      })
      .sort_values(
          'Lead_Time',
          ascending=False
      )
)
supplier_perf[:5]

             Lead_Time
Supplier_ID
263           6.500000
178           6.437500
209           6.388889
265           6.187500
205           6.086957

In [10]:
category_revenue = (
    df.groupby('Product_Category')
      ['Revenue']
      .sum()
      .sort_values(
          ascending=False
      )
)
category_revenue

Product_Category
Electronics    59499850.20
Clothing       59402875.11
Furniture      56949757.22
Food           53957655.80
Name: Revenue, dtype: float64

In [12]:
stockout_analysis = (
    df.groupby('Warehouse')
      ['Stockout_Flag']
      .mean()
      .sort_values(
          ascending=False
      )
)
stockout_analysis

Warehouse
A    0.205541
D    0.203287
C    0.202257
B    0.194631
Name: Stockout_Flag, dtype: float64

In [13]:
backorder_analysis = (
    df.groupby('Product_Category')
      ['Backorder_Flag']
      .mean()
      .sort_values(
          ascending=False
      )
)
backorder_analysis

Product_Category
Furniture      0.166741
Food           0.165602
Clothing       0.154286
Electronics    0.152766
Name: Backorder_Flag, dtype: float64